### ISSUE TITLE
fspackagetool compilation message: Invalid Texture Index

### ISSUE THREAD

**Issue by nmgsimulations** [tml1024/Blender2MSFS2#8]
When compiling objects with multiple LOD objects, the compiler complains about an invalid texture index error on LOD01 and LOD02. It works when every object is exported separately. No errors then which suggest that there is a bug in the script for LOD01 and LOD02.

**Comment by btronquo** [comment]
Hi @nmgsimulations , 

This is not a plugin issue but a workflow one.
For Microsoft Flight Simulator, when you create LODS, you need to be sure that there are not on the same material. 

**To keep the same material in a different LOD, the best way is this workflow :** 

1 - Duplicate the object in the x00 collection and put the copied object in the x01 like you do actually
2 - On the duplicated object (let's say object.001), go to material properties
3 - Select the first material available in the list and click on the "new material" button (please see the following screenshot)
4 - Repeat for every material in the list and every duplicated object

![image](https://user-images.githubusercontent.com/5455001/141281311-8f942c0c-bd82-4e8f-99c7-7bd86f3c9f5b.png)

**Comment by nmgsimulations** [comment]
Thank you so much guys! I am learning something new every day! I tried your suggestion, and it now compiles without any issues! Thanks again!

**Comment by btronquo** [comment]
Thanks for the feedback ;)

**Comment by tml1024** [comment]
> Repeat for every material in the list and every duplicated object

Is this by the way something that the exporter could automate? After all, that is what computers are good at, repeating identical steps of a workflow.

**Comment by btronquo** [comment]
There will be to much use case to cover and to much side effects possible but If you want to do it you can ;)

**Comment by tml1024** [comment]
> There will be to much use case to cover and to much side effects possible but If you want to do it you can ;)

Yeah... It's the old "should I spend two days to automate this boring task that will take two hours" dilemma.

--tml

**Comment by nmgsimulations** [comment]
For what it is worth; I am just glad this plugin works, even if it means making multiple copies of the materials. The older 0.40.0 version had a bug in the export of multiple LOD's and you had to export every LOD on its own. For me this is a lot less work to do, so thank you! I appreciate the time and the effort that went into the upkeep of this addon.

**Comment by PhilippeNatura** [comment]
@tml1024  lol I know this dilemma too much :'D 

@nmgsimulations Thank you for these kind words 👍  
The lod bug fix was done by @Mikeaat and I can't thank him enough for this one :)

**Comment by btronquo** [comment]
@tml1024 lol I know this dilemma too much :'D

@nmgsimulations Thank you for these kind words 👍
The lod bug fix was done by @Mikeaat and I can't thank him enough for this one :)

edit: commented just minutes ago with another account ^^'

**Comment by Mikeaat** [comment]
@btronquo 
thanks for the flowers (german thing :D )
the LOD Bug was fixed by PhysicsTeacher i just commited the changes :)
