### ISSUE TITLE
Can't enable addon in Blender 2.92 anymore

### ISSUE THREAD

**Issue by ozpolonski** [tml1024/Blender2MSFS2#9]
I deleted and reinstalled my Blender from scratch, 2.92 version of Blender, Windows 10. I'm unable to activate this tool for some reason now.

For this version (and also 0.40.0) I'm getting traceback errors.
![Greenshot(002988)-20211122](https://user-images.githubusercontent.com/74175203/142887567-f3a19c76-9df5-45ba-a35e-19e03b760155.png)

**Comment by btronquo** [comment]
1. Close Blender
2. Go to **C:\Users\<your win10 user name>\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons**
3. Delete the folder **Blender2MSFS2**
4. Open Blender (don't load your file, just open blender in a blank project)
5. Add the plugin again downloader from the release here ; https://github.com/tml1024/Blender2MSFS2/releases/download/0.41.4/Blender2MSFS2.zip

**Comment by ozpolonski** [comment]
Unfortunately the same traceback occurs.
Both trying to install into 'users' location OR in the 'programfiles' location
Project not loaded when trying to activate - just the default box, light and camera or with them deleted.

Thanks for the speedy reply

**Comment by btronquo** [comment]
Hum very weird
Could be a conflict with another plugin ?

**Comment by ozpolonski** [comment]
No other plugins (other than default). MSFS is all I use this for.

**Comment by TangoFx** [comment]
Getting the same exact errors when I try to install it on Blender 2.93.5. Works fine though on Blender 2.83.6.

![screenShot](https://user-images.githubusercontent.com/95281519/144030229-fa1a1eb3-3eb4-45dc-a250-d23aacb1b236.jpg)

**Comment by btronquo** [comment]
Hi guys, 

I tried again today with clean blender install on fresh machine and it's working well
I don't understand the cause of this issue

As you may now, Asobo team is now working on a new official blender plugin and I have no time actually to work on this one. Therefore, there will be no more development from my side on this plugin

**Comment by btronquo** [comment]
@TangoFx  
I was able to reproduce your issue 

-> You need to activate the extention gltf2 in preferences
